### ISSUE TITLE
Trailing slash not allowed when adding new component

### ISSUE THREAD

**Issue by janvorisek** [contributte/componette-site#114]
Add new component doesn't allow trailing slashes in URLs to Github repositories. I don't know if Github switched to trailing slashes just recently or if this is browser related (using latest Firefox).

This may discourage some people to add new components to componette.

I think componette should accept both
`https://github.com/janvorisek/ThumbnailHelper/`
and
`https://github.com/janvorisek/ThumbnailHelper`

**Comment by f3l1x** [comment]
Thanks for report. @rozsival can you please take a look?
