### ISSUE TITLE
Wrong URLs in README.md preview on componette 

### ISSUE THREAD

**Issue by dakorpar** [contributte/componette-site#222]
If U take a look at any relative blob links they're wrong on componette site...
Look for instance:
https://componette.org/contributte/mail/

link to .docs/README.md is
https://github.com/contributte/mail/.docs/README.md
instead off
https://github.com/contributte/mail/blob/master/.docs/README.md

![image](https://user-images.githubusercontent.com/9303856/102547664-d2852280-40b9-11eb-9425-c99eda8b54f4.png)

**Comment by f3l1x** [comment]
Yep, you're right. Feel free to fix it.

**Comment by dakorpar** [comment]
I'm not into that code and don't have time to do it... Just saw it's there so I left issue, but PR won't come from me for this...

**Comment by f3l1x** [comment]
Fixed. Thanks.
