### ISSUE TITLE
Report (delete) - petrhejna/*

### ISSUE THREAD

**Issue by ph-legacy** [contributte/componette-site#292]
Those addons are deprecated, you can delete them. Thank you.

- https://componette.org/petrhejna/php-math-interval/
- https://componette.org/petrhejna/nette-date-time-input/
- https://componette.org/petrhejna/nette-money-input/
- https://componette.org/petrhejna/nette-tag-input/
- https://componette.org/petrhejna/bootstrap3-form-decorator/
- https://componette.org/petrhejna/template-helper/
- https://componette.org/petrhejna/json-assert/

**Comment by f3l1x** [comment]
Done. Thank you for the fish.

![Uploading image.png…]()
