### ISSUE TITLE
Automatic tools

### ISSUE THREAD

**Issue by f3l1x** [contributte/componette-site#92]
## Tools

- phpmetrics (http://www.phpmetrics.org/report/latest/index.html)
- apigen (http://www.apigen.org/api/)
- xyz??

I've just walked around PhpMetrics and I like their report very much. Ofcourse, I like ApiGen for its simplicity.

------

Let's consider this. We have http://componette.com/kdyby/doctrine and it could be great to have generated API docs. So you can easily go through all classes and methods. PhpMetrics could give us a short overview of complexity. That all without any special work/change from addon authors.

Maybe like this? 

- componette.com/kdyby/doctrine/api
- componette.com/kdyby/doctrine/phpmetrics

Or with subdomains?

- api.componette.com/kdyby/doctrine
- phpmetrics.componette.com/kdyby/doctrine

It could increase value of componette and the whole ecosystem. Am I wrong?

What do you think guys? It's just an idea.

@chemix @JanTvrdik @hrach @matej21 @milo @paveljanda @tomasvotruba @enumag @dg

**Comment by hrach** [comment]
Personally, I wouldn't add such things. There are already tools such as https://codedoc.pub/. But you may suggest them! :)

> It could increase value of componette and the whole ecosystem.

Yey, but also: It could increase complexity of componette and the whole ecosystem.

**Comment by hrach** [comment]
> But you may suggest them! :)

Or better, allow sime linking to them pro the component profile :) Also some link to the docs/official site in the right column :)

**Comment by TomasVotruba** [comment]
I would like to hear more about motivation. Why do you want to add such tools?

**Comment by enumag** [comment]
Personally I like the idea. When I see a new interesting library I mostly just jump right into the code. Apigen is better for browsing the code than GitHub and most authors wont bother themselves with setting up automatic generation of API for every release. It would be nice to have it automated on componette.

**Comment by paveljanda** [comment]
I have it like that within some of ublaboo libraries (https://ublaboo.org/api/datagrid/ etc).
It does not take any additional effort to generate these api docs automatically..

So yes, I would be glad if the api doc is there in each project.

But I would raise another questions - you mentioned the ecosystem. Maybe putting the project doc into one place? Or teaching nette community how to create the documentation in one uniform form?

If these questions are solved, there could be a uniform way how to access the api doc, etc.

**Comment by dg** [comment]
Automatically generated API documentation sounds great. (But does ApiGen support PHP 7 syntax?). The graphs from the Phpmetrics are not interesting or useful for me, and I really cannot imagine that anyone except the author of the library might be interested.

**Comment by enumag** [comment]
@dg Thanks to @TomasVotruba it does now except for one issue which should be resolved soon.

**Comment by f3l1x** [comment]
> Personally, I wouldn't add such things. There are already tools such as https://codedoc.pub/. But you may suggest them! 

Unfortunately https://codedoc.pub is dead. :(

**Comment by paveljanda** [comment]
As already mentioned, I think that this could bring unnecessary complexity to the ecosystem. Maybe when there is more than 50 core developers in Contributte?

**Comment by f3l1x** [comment]
Closing it here. It's outdated since now.
